const data = [
    {
        id: 1,
        title: "Are You Ready To Go Home After The Sunset View?",
        img: "news1.png",
        authorTitle: "Joseph",
        author: "author.jpg",
        date: "25 April 2022",
    },
    {
        id: 2,
        title: "Life is as free as eagles, or is it just loneliness?",
        img: "news2.png",
        authorTitle: "Joseph",
        author: "author.jpg",
        date: "25 April 2022",
    },
    {
        id: 3,
        title: "16 Unheard Ways To Achieve Greater Walker",
        img: "news3.png",
        authorTitle: "Joseph",
        author: "author.jpg",
        date: "25 April 2022",
    },
    {
        id: 4,
        title: "Master The Art Of Nature With These 7 Tips",
        img: "news4.png",
        authorTitle: "Joseph",
        author: "author.jpg",
        date: "25 April 2022",
    },
    {
        id: 5,
        title: "16 Unheard Ways To Achieve Greater Walker",
        img: "news5.png",
        authorTitle: "Joseph",
        author: "author.jpg",
        date: "25 April 2022",
    },
    {
        id: 6,
        title: "Master The Art Of Nature With These 7 Tips",
        img: "news6.png",
        authorTitle: "Joseph",
        author: "author.jpg",
        date: "25 April 2022",
    },
    {
        id: 7,
        title: "Your Light Is About To Stop Being Relevant",
        img: "news7.png",
        authorTitle: "Joseph",
        author: "author.jpg",
        date: "25 April 2022",
    },
    {
        id: 8,
        title: "Your Light Is About To Stop Being Relevant",
        img: "news8.png",
        authorTitle: "Joseph",
        author: "author.jpg",
        date: "25 April 2022",
    },
    {
        id: 9,
        title: "Master The Art Of Nature With These 7 Tips",
        img: "news9.png",
        authorTitle: "Joseph",
        author: "author.jpg",
        date: "25 April 2022",
    }
];
export default data;