const data = [
    {
        id: 1,
        title: "Helpful Tips for Working from Home as a Freelancer",
        img: "img1.jpg",
        category: "Working Tips",
        author: "author.jpg",
        date: "25 April 2022",
    },
    {
        id: 2,
        title: "10 Easy Ways to Be Environmentally Conscious At Home",
        img: "img2.jpg",
        category: "Development",
        author: "author.jpg",
        date: "25 April 2022",
    },
    {
        id: 3,
        title: "How to Give Your Space a Parisian-Inspired Makeover",
        img: "img3.jpg",
        category: "Lifestyle",
        author: "author.jpg",
        date: "25 April 2022",
    },
    {
        id: 4,
        title: "Facts About Business That Will Help You Success",
        img: "img4.jpg",
        category: "Business",
        author: "author.jpg",
        date: "25 April 2022",
    },
    {
        id: 5,
        title: "The Next 60 Things To Immediately Do About Building A Plan",
        img: "img5.jpg",
        category: "Building",
        author: "author.jpg",
        date: "25 April 2022",
    },
    {
        id: 6,
        title: "Master The Art Of Nature With These 7 Tips",
        img: "img6.jpg",
        category: "Joseph",
        author: "author.jpg",
        date: "25 April 2022",
    },
    {
        id: 7,
        title: "Your Light Is About To Stop Being Relevant",
        img: "img7.jpg",
        category: "Joseph",
        author: "author.jpg",
        date: "25 April 2022",
    },
    {
        id: 8,
        title: "Your Light Is About To Stop Being Relevant",
        img: "img8.jpg",
        category: "Joseph",
        author: "author.jpg",
        date: "25 April 2022",
    },
    {
        id: 9,
        title: "Master The Art Of Nature With These 7 Tips",
        img: "img9.jpg",
        category: "Joseph",
        author: "author.jpg",
        date: "25 April 2022",
    }
];
export default data;